name: Create Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'run action manually'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Compress project
        run: |
          git archive -o "Source code.zip" main
          git archive -o "Source code.tar.gz" main

      - name: Upload Release Asset (zip)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.checkout.outputs.upload_url }}
          asset_path: ${{ github.workspace }}Source code.zip
          asset_name: Source code.zip
          asset_content_type: application/zip

      - name: Upload Release Asset (tar.gz)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.checkout.outputs.upload_url }}
          asset_path: ${{ github.workspace }}Source code.tar.gz
          asset_name: Source code.tar.gz
          asset_content_type: application/gzip
